apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: nginx:1.25.1-alpine
        name: container1

