apiVersion: v1
kind: ReplicationController
metadata:
  name: rc1

spec:
  selector:
    app: backend 
  replicas: 3
  template:
    metadata:
      name: pod3
      labels:
        app: backend
    spec:
      containers:
      - image: tomcat
        name: tomcat123
