apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: pod1
      labels:
        app: backend
    spec:
      containers:
      - name: container1
        image: nginx
      
         
